Require a real version of Resolwe
Otherwise, installation can fail with:
error: resolwe 1.3.1 is installed but resolwe==master is required by
set(['resolwe-bio']).